project:
  type: book
  output-dir: docs

book:
  title: "System Dynamics"
  author: "Benjamin Aziel"
  date: now
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - chaux.qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly

  pdf:
    documentclass: scrreprt

markdown_extensions:
    - admonition
