# Our Second Order of Business

## Preface {-}

First order systems are honestly pretty boring. When we put in a step input, we just get a pure exponential. We won't be able to get more interesting behavior, like oscillation, because that's just mathematically impossible.^[Prove it!]

Second order systems, on the other hand, *can* oscillate by themselves. Try to convince yourself of this mathematically just based on what oscillation is.

Mass-spring systems are pretty good models of everything in the world (as long as you use enough mass-spring systems). They're really nice because having a good understanding of ONE mass-spring system provides us with the intuition for more complicated systems.

## Mass and Spring

Say we have a mass-spring system where a mass $m$ is attached to a wall with a spring $k$ and a damper $b$. Gravity isn't "turned on", so if you want to visualize the system, that mass is floating. The equation of motion for a positive displacement $q$ is:^[Prof. Luchtenburg went off on a tangent about Hooke being a genius for realizing that spring motion is linear near the origin here. That was pretty funny.]

$$m\ddot{q} = -kq - b\dot{q}$$

Or in its more familiar form:

$$m\ddot{q} + b\dot{q} + kq = 0$$

This is the famed mass-spring equation. Say we have an input - a force $u$ acting on the mass in the positive direction. Now our equation of motion is:

$$m\ddot{q} + b\dot{q} + kq = u$$

This is a linear differential equation, so we'll solve this by plugging in an educated guess. Let's try $q(t) = Ae^{st}$, because differentiating this function $n$ times just multiplies it by $s^n$.

First, we'll solve the homogeneous equation, or the case where $u=0$.^[If you're curious why we do this, you can read up on it in a linear algebra textbook. Think it's theorem 3.9 in Friedberg's Linear Algebra.]

$$m\ddot{q} + b\dot{q} + kq = 0$$
$$ms^2 Ae^{st} + bs Ae^{st} + kAe^{st} = 0$$
$$ms^2 + bs + k = 0$$

This is known as the characteristic (or auxiliary) equation. We can now use algebra to solve for the roots of the equation, or by proxy, the solution of the differential equation.

$$s_{1, 2} = \frac{-b \pm \sqrt{b^2 - 4mk}}{2m}$$

These are also called the **poles** of the system, but we're getting ahead of ourselves. Let's simplify further.

$$s_{1, 2} = \frac{-b \pm \sqrt{b^2 - 4mk}}{2m} = -\frac{b}{2m} \pm \sqrt{\frac{b^2 - 4mk}{4m^2}} = -\frac{b}{2m} \pm \sqrt{\left(\frac{b}{2m} \right)^2 - \frac{k}{m}}$$

We define the **natural frequency** $\omega_n = \sqrt{\frac{k}{m}}$ and the **damping ratio** $\zeta = \frac{b}{2m\omega_n}$. Using these definitions, we can reorganize the mass-spring equation in terms of these variables.

$$m\ddot{q} + b\dot{q} + kq = 0 \qquad \to \qquad \ddot{q} + 2\zeta\omega_n \dot{q} + \omega_n^2 q = 0$$

And the poles of this equation are:

$$s_{1, 2} = -\zeta \omega_n \pm \omega_n \sqrt{\zeta^2 - 1}$$

## A Quick Dive into Complex Analysis

Complex analysis is the study of functions of a complex variable $z$, where $z$ has a real component $a$ and an imaginary component $b$. Complex numbers show up all the time in this course, whenever anything oscillates, really (like mass-spring systems or pendulums).



To take our first plunge into complex analysis, we need to define the **imaginary unit** $i$.^[You'll see people, especially electrical engineers, use $j$ instead, because $i$ is commonly used for current. We're better than them.] For now, let's define $i$ as one of the two solutions to the quadratic equation $x^2 = -1$. (The other is $-i$, of course.) This is really special, because now we can describe the solutions of ALL polynomials^[Regardless if its coefficients are real or complex!] as the sum of a real number $a$ and another real number $b$ multiplied by the imaginary unit $i$.

Let's conjure up a graphical representation of these numbers using Cartesian coordinates, where we define one axis as "real" and the other as "imaginary". We'll call this the complex plane. An arbitrary point $z = a+ ib$ is plotted below.

We can also interpret these numbers in the context of polar coordinates, where $\theta$ is the angle between the vector from the origin to $z$ and the real axis, and $r$ is the magnitude of the aforementioned vector. It's not difficult to translate between Cartesian coordinates and polar coordinates, but I'll dump the formulas here anyway.


$$a = r \cos{\theta} \qquad b = r \sin{\theta} \qquad r = \sqrt{a^2 + b^2} \qquad \theta = \arctan\left({\frac{b}{a}}\right)$$

It'd be criminal to not mention Euler's formula, which posits that: ^[You can prove this using the Taylor series representation of $e^{x}$. You should do it, it's *very* rewarding]


$$e^{i\theta} = \cos{\theta} + i \sin{\theta}$$

A lot of the nuance of complex numbers is best understood by analyzing this **complex exponential**, especially because:


$$z = a+ib = r\cos{\theta} + ir \sin{\theta} = r (\cos{\theta} + i \sin{\theta}) = re^{i\theta}$$

## Damping!

When $\zeta = 0$ (or the system is **undamped**), we have the poles $s_{1, 2} = \pm i\omega_n$. This implies that our solution is a linear combination of sines and cosines, endlessly oscillating, forever and ever. (That's kind of depressing to be honest.)


> What next? Euler guy.
>
> Prof. Luchtenburg


$$x(t) = A_1 e^{i\omega_n t} + A_2 e^{- i \omega_n t} = A_1 (\cos(\omega_n t) + i \sin(\omega_n t)) + A_2 (\cos(\omega_n t) - i \sin(\omega_n t))$$
\vspace{-0.3in}
$$= (A_1 + A_2) \cos(\omega_n t) + i(A_1 - A_2) \sin(\omega_n t) = C_1 \cos(\omega_n t) + C_2 \sin(\omega_n t)$$

This reasoning carries over if we pick a damping ratio $\zeta$ between 0 and 1 (or the system is **underdamped**). The poles are:


$$s_{1, 2} = -\zeta \omega_n \pm \sqrt{\omega_n^2 (\zeta^2 - 1)} = -\zeta \omega_n \pm i \omega_n \sqrt{1 - \zeta^2} = \sigma \pm i \omega_d$$ 

We define the **damped frequency** $\omega_d = \omega_n \sqrt{1-\zeta^2}$. (In practice, $\omega_d \approx \omega_n$, because $\zeta \ll 1$.) Additionally, we define $\sigma = \zeta\omega_n$ (for some reason). After substituting these new variables in, our solution becomes:


$$x(t) = A_1 e^{(-\sigma + i\omega_d) t} + A_2 e^{(-\sigma - i\omega_d) t} = e^{-\sigma t} (C_1 \cos(\omega_n t) + C_2 \sin(\omega_n t))$$

In the lattermost form, it's obvious that $\sigma$ in fact \textit{does} have a use other than bookkeeping; it defines the exponential **envelope** by which the oscillation decays. An envelope is a function that outlines how a function grows/decays (it's the red dashed line in the figure below).

Notably, the time constant $\tau$ of the envelope is equal to $1/\sigma$. Thus, we can eyeball the value of $\sigma$ based on how we'd find the time constant (the value $63\%$ less than the $y$-intercept of the envelope).
$$x(t) = e^{-\sigma t} \sin(\omega_d t + \varphi)$$

Most mechanical systems tend to have a very low damping ratio ($\zeta \simeq O(0.1)$)^[Related rates of growth from Ma111, or big-O notation if you've taken ECE264.], and as mentioned before, a good rule of thumb is that $\omega_n = \omega_d$.

When we apply some initial conditions (like $q(0) = q_0$ and $\dot{q}(0) = v_0$), our solution becomes:

$$q(t) = e^{\sigma t} \left(q_0 \cos(\omega_d t) + \frac{\sigma q_0 + v_0}{\omega_d} \sin(\omega_d t)\right)$$

When $\zeta = 1$, or the system is **critically damped**, the poles are:

$$s_{1, 2} = -\zeta \omega_n$$

We use a trick from differential equations to fake another linearly independent solution, just chuck on an extra $t$.

$$q(t) = A_1 e^{-\zeta \omega_n t} + A_2 t e^{-\zeta \omega_n t}$$

This doesn't really happen in the real world, but it's nice to cover all our bases. How about when $\zeta > 1$? We call this case **overdamped**, because our poles are:

$$s_{1, 2} = -\zeta \omega_n \pm \omega_n \sqrt{\zeta^2 - 1}$$

Both poles are negative here! Our solution is:

$$q(t) = A_1 e^{s_1 t} + A_2 e^{s_2 t}$$

## Pole Plots

I've been emphasizing poles a lot in the last few pages, but why? What's the importance of these seemingly arbitrary values? In fact, we can infer the dynamics of a system based on its poles.^[This is the crux of a lot we do in ME351. If any of you remember what an eigenvalue is from Ma110, that'll come in handy in a bit.]


To analyze poles, we use a graphical tool called a **pole plot**, the plot of the roots of the characteristic equation on the complex plane. Let's go down the list:

* When both poles are on the imaginary axis, the system is undamped.
* When both poles are off the real axis, the system oscillates. If they're to the left of the imaginary axis, it'll decay exponentially (underdamped), and if they're to the right of the imaginary axis, it'll grow exponentially.
* If both poles are on the real axis to the left of the imaginary axis, it's overdamped.
* Rule of thumb: if there is ANY pole to the right of the imaginary axis, the response blows up.

Here's a nice chart from FPE. Complex conjugates are omitted for simplicity.

## Leveraging the Discriminant

I'm going to stray off from Prof. Luchtenburg for a second because *I* think this is useful.

Suppose we want to identify the dampedness of a system based on the equation of motion rather than solving for $\zeta$. We can do exactly this using the **discriminant** of the characteristic equation of the system. Let's take a look at the canonical mass-spring system with a damper once again.

The equation of motion, assuming free motion, is:
$$m\ddot{q} + b \dot{q} + k q = 0$$

The characteristic equation is derived after plugging in $q = e^{st}$.
$$ms^2 + bs + k = 0$$

As stated in the section on damping, there are three forms of the general solution if there is damping present: both poles are real and distinct (the system is overdamped), both poles are real and equal (the system is critically damped), or both poles are complex conjugates (the system is underdamped). You may recall from Algebra that the discriminant of a polynomial can reveal some properties of the roots without actually computing them. The discriminant of a quadratic is defined as follows:
$$\text{Disc}(ax^2 + bx + c) = b^2-4ac$$

This is the argument of the square root in the quadratic formula. If this expression is positive, the solutions to the quadratic are real and distinct. If this expression is 0, then there is only one real solution to the quadratic. If this expression is negative, the solutions to the quadratic are complex. So physically, finding the discriminant of the characteristic equation of the mass-spring system will tell us how damped it is.
$$\text{Disc}(ms^2 + bs + k) = b^2-4mk$$

\begin{align*}
    b^2 - 4mk > 0 \quad &\to \quad \text{overdamped} \\
    b^2 - 4mk = 0 \quad &\to \quad \text{critically damped} \\
    b^2 - 4mk < 0 \quad &\to \quad \text{underdamped}
\end{align*}

And of course, if $b=0$, then the system is undamped. 

## The Tank, Revisited (Inertia)

Let's revisit the tank from our study of first order systems. However, we'll make one small change: the outflow pipe now has a defined length of $L_p$.

Let's model the same way we've been doing thus far. First, a conservation law:


$$\dot{V} = -Q$$

Next, "Ohm's law":


$$Q = \frac{\Delta P}{R} = \frac{P - P_\text{atm}}{R}$$

If we isolate a piece of the pipe (with length $L_p$) as shown below, we can demystify this system a bit.

Assuming the cross-sectional area of the pipe $A_p$ is constant, the pressure force $F_p = A_p \Delta P$ accelerates the fluid between the two ends of this pipe. Additionally, there is friction $F_f = -QRA_p$ on the liquid caused by the resistance of the pipe. By leveraging Newton's second law of motion, we now have a relationship between the pressure difference $\Delta P$ and the velocity of the water $v$.


$$m \frac{dv}{dt} = F_p + F_f = A_p \Delta P - Q R A_p$$

The mass $m$ of the fluid between the two ends of this pipe is equal to the product of the density of the fluid $\rho$ and the volume between the two ends $V_p$. (Notably, the volume $V_p = A_p L_p$.)


$$\rho \, V_p \, \frac{dv}{dt} = \rho A_p L_p \, \frac{dv}{dt} = A_p \Delta P - RQ A_p$$

Because the product of the cross-sectional area $A_p$ and the fluid velocity $v$ is equal to the volumetric flow rate $Q$, we can rewrite this equation as follows:


$$\frac{\rho L_p}{A_p} \, \frac{dQ}{dt} = \Delta P - RQ$$

Ok, we can shed some light on what we're doing now. We define **inductance** (also referred to as **liquid-flow inertance** or **inertia**) as a term that describes the change in potential required for a unit rate of fluid flow. Inductance is the tendency of the fluid to move; it's created by the inertia of water flowing through the pipe. The mathematical definition of inductance is as follows:


$$L = \frac{\rho L_p}{A_p}$$

Note that this definition of inductance is only valid for flow systems, but analogous concepts occur in other fields (like inductors from circuit analysis)! Fluid components that have an inductance are analogous to these inductors, or mechanical components with inertia. 



Let's wrap up this example. When we plug in the definition of $L$ into our equation, a simple first order system rears its head.^[The analog of this system in circuit analysis is called the RL circuit, which is often used as a passive filter.]


$$L \, \frac{dQ}{dt} + RQ = \Delta P$$

Let's throw it into canonical form so we can see its time constant.


$$\left(\frac{L}{R}\right) \dot{Q} + Q = \frac{\Delta P}{R} \qquad \qquad \tau = \frac{L}{R}$$

To summarize, we've added a new tool to our arsenal: conservation of momentum (or Newton's second law). 

$$\Delta P = L \dot{Q} + RQ$$
$$\dot{V} = -Q$$
$$C \Delta P = V$$

By combining these three equations, we can use tools from our studies of mass-spring systems to analyze... well... any second order system.


$$L \Delta \ddot{P} + R \Delta \dot{P} + \frac{1}{C} \Delta P = 0 \qquad \to \qquad \Delta \ddot{P} + \left(\frac{R}{L}\right) \Delta \dot{P} + \left(\frac{1}{LC}\right) \Delta P = 0$$
$$m \ddot{q} + b \dot{q} + k q = 0 \qquad \to \qquad \ddot{q} + \left(\frac{b}{m}\right) \dot{q} + \left(\frac{k}{m}\right) q = 0$$

We simply retrofit the definitions of the natural frequency $\omega_n$ and damping ratio $\zeta$ based on how we defined them for mass-spring systems to determine how the oscillations behave. Here's a quick example using the flow system analogy we've been using thus far:
$$\qquad \ddot{q} + 2\zeta\omega_n \dot{q} + \omega_n^2 q = 0 \quad \longleftrightarrow \quad  \Delta \ddot{P} + \left(\frac{R}{L}\right) \Delta \dot{P} + \left(\frac{1}{LC}\right) \Delta P = 0$$

\begin{align*}
    2 \zeta \omega_n = \frac{R}{L} \qquad &\longrightarrow \qquad \zeta = \frac{R}{2L \omega_n} = \frac{R\sqrt{LC}}{2L} = \frac{R}{2} \sqrt{\frac{C}{L}}\\
    \omega_n^2 = \frac{1}{LC} \qquad &\longrightarrow \qquad \omega_n = \frac{1}{\sqrt{LC}} = \frac{\sqrt{LC}}{LC}
\end{align*}
